// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDesktopAPI(arg1) {
  return window['go']['windowexpansions']['App']['CreateDesktopAPI'](arg1);
}

export function CreateDesktopHideAPI(arg1) {
  return window['go']['windowexpansions']['App']['CreateDesktopHideAPI'](arg1);
}

export function CreateHideWebview(arg1) {
  return window['go']['windowexpansions']['App']['CreateHideWebview'](arg1);
}

export function ExpansionsClose() {
  return window['go']['windowexpansions']['App']['ExpansionsClose']();
}

export function ExpansionsPostMessage(arg1) {
  return window['go']['windowexpansions']['App']['ExpansionsPostMessage'](arg1);
}

export function ExpansionsRun(arg1) {
  return window['go']['windowexpansions']['App']['ExpansionsRun'](arg1);
}

export function ExpansionsStatus() {
  return window['go']['windowexpansions']['App']['ExpansionsStatus']();
}

export function GetExpansionList(arg1) {
  return window['go']['windowexpansions']['App']['GetExpansionList'](arg1);
}

export function SendHideMessage(arg1, arg2) {
  return window['go']['windowexpansions']['App']['SendHideMessage'](arg1, arg2);
}

export function SetThemeVariables(arg1, arg2) {
  return window['go']['windowexpansions']['App']['SetThemeVariables'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['windowexpansions']['App']['Startup'](arg1);
}
