// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExpansionsClose() {
  return window['go']['windowexpansions']['App']['ExpansionsClose']();
}

export function ExpansionsPostMessage(arg1) {
  return window['go']['windowexpansions']['App']['ExpansionsPostMessage'](arg1);
}

export function ExpansionsRun(arg1) {
  return window['go']['windowexpansions']['App']['ExpansionsRun'](arg1);
}

export function ExpansionsStatus() {
  return window['go']['windowexpansions']['App']['ExpansionsStatus']();
}

export function Startup(arg1) {
  return window['go']['windowexpansions']['App']['Startup'](arg1);
}
