// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['windowcontroller']['App']['CheckForUpdates']();
}

export function ControllerClose() {
  return window['go']['windowcontroller']['App']['ControllerClose']();
}

export function ControllerMaximize() {
  return window['go']['windowcontroller']['App']['ControllerMaximize']();
}

export function ControllerMinimize() {
  return window['go']['windowcontroller']['App']['ControllerMinimize']();
}

export function ControllerOnClick(arg1, arg2) {
  return window['go']['windowcontroller']['App']['ControllerOnClick'](arg1, arg2);
}

export function GetVersions() {
  return window['go']['windowcontroller']['App']['GetVersions']();
}

export function OnDownloadProgress(arg1) {
  return window['go']['windowcontroller']['App']['OnDownloadProgress'](arg1);
}

export function Startup(arg1) {
  return window['go']['windowcontroller']['App']['Startup'](arg1);
}

export function UpdateVersion() {
  return window['go']['windowcontroller']['App']['UpdateVersion']();
}
