// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ControllerClose():Promise<void>;

export function ControllerMaximize():Promise<void>;

export function ControllerMinimize():Promise<void>;

export function ControllerOnClick(arg1:number,arg2:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
