// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControllerOnClick(arg1, arg2) {
  return window['go']['windowcontroller']['App']['ControllerOnClick'](arg1, arg2);
}

export function GetVersions() {
  return window['go']['windowcontroller']['App']['GetVersions']();
}

export function Startup(arg1) {
  return window['go']['windowcontroller']['App']['Startup'](arg1);
}
