// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BotClose() {
  return window['go']['windowbot']['App']['BotClose']();
}

export function BotResetBot() {
  return window['go']['windowbot']['App']['BotResetBot']();
}

export function BotResetTemplate() {
  return window['go']['windowbot']['App']['BotResetTemplate']();
}

export function BotResetTemplateAndBot() {
  return window['go']['windowbot']['App']['BotResetTemplateAndBot']();
}

export function BotRun(arg1) {
  return window['go']['windowbot']['App']['BotRun'](arg1);
}

export function BotStatus() {
  return window['go']['windowbot']['App']['BotStatus']();
}

export function Startup(arg1) {
  return window['go']['windowbot']['App']['Startup'](arg1);
}
