// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BotClose():Promise<boolean>;

export function BotResetTemplate():Promise<boolean>;

export function BotRun(arg1:Array<string>):Promise<boolean>;

export function BotStatus():Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
