// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BotClose() {
  return window['go']['windowbot']['App']['BotClose']();
}

export function BotRun(arg1) {
  return window['go']['windowbot']['App']['BotRun'](arg1);
}

export function BotStart() {
  return window['go']['windowbot']['App']['BotStart']();
}

export function BotStatus() {
  return window['go']['windowbot']['App']['BotStatus']();
}

export function BotStop() {
  return window['go']['windowbot']['App']['BotStop']();
}

export function Startup(arg1) {
  return window['go']['windowbot']['App']['Startup'](arg1);
}
