// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {windowyarn} from '../models';

export function Startup(arg1:context.Context):Promise<void>;

export function YarnCommands(arg1:windowyarn.YarnCommandsParams):Promise<void>;
