// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['windowyarn']['App']['Startup'](arg1);
}

export function YarnCommands(arg1) {
  return window['go']['windowyarn']['App']['YarnCommands'](arg1);
}
