// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitCheckout(arg1, arg2, arg3) {
  return window['go']['windowgit']['App']['GitCheckout'](arg1, arg2, arg3);
}

export function GitClone(arg1, arg2) {
  return window['go']['windowgit']['App']['GitClone'](arg1, arg2);
}

export function GitDelete(arg1, arg2) {
  return window['go']['windowgit']['App']['GitDelete'](arg1, arg2);
}

export function GitFetch(arg1, arg2) {
  return window['go']['windowgit']['App']['GitFetch'](arg1, arg2);
}

export function GitReposList(arg1) {
  return window['go']['windowgit']['App']['GitReposList'](arg1);
}

export function Startup(arg1) {
  return window['go']['windowgit']['App']['Startup'](arg1);
}
