// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitAddRemote(arg1, arg2) {
  return window['go']['windowgit']['App']['GitAddRemote'](arg1, arg2);
}

export function GitBranch(arg1) {
  return window['go']['windowgit']['App']['GitBranch'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['windowgit']['App']['GitCheckout'](arg1, arg2);
}

export function GitClone(arg1, arg2) {
  return window['go']['windowgit']['App']['GitClone'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['windowgit']['App']['GitCommit'](arg1, arg2);
}

export function GitDelete(arg1) {
  return window['go']['windowgit']['App']['GitDelete'](arg1);
}

export function GitDiff(arg1, arg2) {
  return window['go']['windowgit']['App']['GitDiff'](arg1, arg2);
}

export function GitFetch(arg1) {
  return window['go']['windowgit']['App']['GitFetch'](arg1);
}

export function GitGetWordSpaces() {
  return window['go']['windowgit']['App']['GitGetWordSpaces']();
}

export function GitInit(arg1) {
  return window['go']['windowgit']['App']['GitInit'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['windowgit']['App']['GitLog'](arg1, arg2);
}

export function GitPull(arg1, arg2, arg3) {
  return window['go']['windowgit']['App']['GitPull'](arg1, arg2, arg3);
}

export function GitPush(arg1) {
  return window['go']['windowgit']['App']['GitPush'](arg1);
}

export function GitReposList(arg1) {
  return window['go']['windowgit']['App']['GitReposList'](arg1);
}

export function GitSetWordSpaces(arg1) {
  return window['go']['windowgit']['App']['GitSetWordSpaces'](arg1);
}

export function GitShow(arg1, arg2) {
  return window['go']['windowgit']['App']['GitShow'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['windowgit']['App']['GitStatus'](arg1);
}

export function GitTags(arg1) {
  return window['go']['windowgit']['App']['GitTags'](arg1);
}

export function Startup(arg1) {
  return window['go']['windowgit']['App']['Startup'](arg1);
}
