// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GitAddRemote(arg1:string,arg2:string):Promise<boolean>;

export function GitBranch(arg1:string):Promise<Record<string, any>>;

export function GitCheckout(arg1:string,arg2:string):Promise<boolean>;

export function GitClone(arg1:string):Promise<boolean>;

export function GitCommit(arg1:string,arg2:string):Promise<boolean>;

export function GitDelete(arg1:string):Promise<boolean>;

export function GitDiff(arg1:string,arg2:string):Promise<string>;

export function GitFetch(arg1:string):Promise<boolean>;

export function GitGetWordSpaces():Promise<string>;

export function GitInit(arg1:string):Promise<boolean>;

export function GitLog(arg1:string,arg2:string):Promise<string>;

export function GitPull(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GitPush(arg1:string):Promise<boolean>;

export function GitReposList():Promise<Array<string>>;

export function GitSetWordSpaces(arg1:string):Promise<void>;

export function GitShow(arg1:string,arg2:string):Promise<string>;

export function GitShowTags(arg1:string,arg2:string):Promise<string>;

export function GitStatus(arg1:string):Promise<string>;

export function GitTags(arg1:string):Promise<Array<string>>;

export function Startup(arg1:context.Context):Promise<void>;
