// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {windowgit} from '../models';
import {context} from '../models';

export function GitCheckout(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GitClone(arg1:string,arg2:string):Promise<boolean>;

export function GitDelete(arg1:string,arg2:string):Promise<boolean>;

export function GitFetch(arg1:string,arg2:string):Promise<boolean>;

export function GitReposList(arg1:string):Promise<Array<windowgit.GitRepoInfo>>;

export function Startup(arg1:context.Context):Promise<void>;
