// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDownloadFiles(arg1) {
  return window['go']['windowapp']['App']['AppDownloadFiles'](arg1);
}

export function AppExists(arg1) {
  return window['go']['windowapp']['App']['AppExists'](arg1);
}

export function AppFetch(arg1, arg2) {
  return window['go']['windowapp']['App']['AppFetch'](arg1, arg2);
}

export function AppGetConfig(arg1) {
  return window['go']['windowapp']['App']['AppGetConfig'](arg1);
}

export function AppReStart() {
  return window['go']['windowapp']['App']['AppReStart']();
}

export function AppReadFiles(arg1) {
  return window['go']['windowapp']['App']['AppReadFiles'](arg1);
}

export function AppResetTemplate() {
  return window['go']['windowapp']['App']['AppResetTemplate']();
}

export function AppSelectDirectory() {
  return window['go']['windowapp']['App']['AppSelectDirectory']();
}

export function AppSetConfig(arg1, arg2) {
  return window['go']['windowapp']['App']['AppSetConfig'](arg1, arg2);
}

export function AppWriteFiles(arg1, arg2) {
  return window['go']['windowapp']['App']['AppWriteFiles'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['windowapp']['App']['Startup'](arg1);
}
