// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDownloadFiles(arg1) {
  return window['go']['windowapp']['App']['AppDownloadFiles'](arg1);
}

export function AppExists(arg1) {
  return window['go']['windowapp']['App']['AppExists'](arg1);
}

export function AppGetPathsState() {
  return window['go']['windowapp']['App']['AppGetPathsState']();
}

export function AppReadFiles(arg1) {
  return window['go']['windowapp']['App']['AppReadFiles'](arg1);
}

export function AppWriteFiles(arg1, arg2) {
  return window['go']['windowapp']['App']['AppWriteFiles'](arg1, arg2);
}

export function GetAppLogsFilePath() {
  return window['go']['windowapp']['App']['GetAppLogsFilePath']();
}

export function Startup(arg1) {
  return window['go']['windowapp']['App']['Startup'](arg1);
}
