// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AppDownloadFiles(arg1:string):Promise<void>;

export function AppExists(arg1:string):Promise<boolean>;

export function AppFetch(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function AppGetConfig(arg1:Array<string>):Promise<any>;

export function AppReStart():Promise<void>;

export function AppReadFiles(arg1:string):Promise<string>;

export function AppResetTemplate():Promise<void>;

export function AppSelectDirectory():Promise<string>;

export function AppSetConfig(arg1:string,arg2:any):Promise<boolean>;

export function AppWriteFiles(arg1:string,arg2:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
