// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {windowapp} from '../models';
import {context} from '../models';

export function AppDownloadFiles(arg1:string):Promise<void>;

export function AppExists(arg1:string):Promise<boolean>;

export function AppGetPathsState():Promise<windowapp.PathsState>;

export function AppReadFiles(arg1:string):Promise<string>;

export function AppWriteFiles(arg1:string,arg2:string):Promise<boolean>;

export function GetAppLogsFilePath():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
