// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Startup(arg1:context.Context):Promise<void>;

export function ThemeDownloadFiles():Promise<void>;

export function ThemeLoadVariables():Promise<void>;

export function ThemeMode():Promise<string>;

export function ThemeResetTheme():Promise<boolean>;

export function ThemeSave(arg1:string):Promise<void>;

export function ThemeSetMode(arg1:string):Promise<void>;
