// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['windowtheme']['App']['Startup'](arg1);
}

export function ThemeLoadVariables() {
  return window['go']['windowtheme']['App']['ThemeLoadVariables']();
}

export function ThemeMode() {
  return window['go']['windowtheme']['App']['ThemeMode']();
}

export function ThemeResetTheme() {
  return window['go']['windowtheme']['App']['ThemeResetTheme']();
}

export function ThemeSave(arg1) {
  return window['go']['windowtheme']['App']['ThemeSave'](arg1);
}

export function ThemeSetMode(arg1) {
  return window['go']['windowtheme']['App']['ThemeSetMode'](arg1);
}
